Update buck, gradle and AGP versions (#6)

diff --git a/buckw b/buckw
--- a/buckw
+++ b/buckw
@@ -4,16 +4,28 @@
 ##
 ##  Buck wrapper script to invoke okbuck when needed, before running buck
 ##
-##  Created by OkBuck Gradle Plugin on : Tue May 30 14:39:04 PDT 2017
-##
 #########################################################################
 
-WORKING_DIR=$(pwd)
+PRG="$0"
+# Need this for relative symlinks.
+while [ -h "$PRG" ] ; do
+    ls=`ls -ld "$PRG"`
+    link=`expr "$ls" : '.*-> \(.*\)$'`
+    if expr "$link" : '/.*' > /dev/null; then
+        PRG="$link"
+    else
+        PRG=`dirname "$PRG"`"/$link"
+    fi
+done
+SAVED="`pwd`"
+cd "`dirname \"$PRG\"`/" >/dev/null
+SCRIPT_DIR="`pwd -P`"
+cd "$SAVED" >/dev/null
 
-red=`tput setab 1 2>/dev/null || true`
-yellow=`tput setab 3 2>/dev/null || true`
-green=`tput setab 2 2>/dev/null || true`
-blue=`tput setab 4 2>/dev/null || true`
+red=`tput setaf 1 2>/dev/null || true`
+yellow=`tput setaf 3 2>/dev/null || true`
+green=`tput setaf 2 2>/dev/null || true`
+blue=`tput setaf 4 2>/dev/null || true`
 reset=`tput sgr0 2>/dev/null || true`
 bold=`tput bold 2>/dev/null || true`
 
@@ -25,16 +37,16 @@ die ( ) {
 }
 
 info ( ) {
-    echo "${bold}${blue} $* ${reset}"
+    echo "${bold}${blue}$*${reset}"
 }
 
 warn ( ) {
-    echo "${bold}${yellow} $* ${reset}"
+    echo "${bold}${yellow}$*${reset}"
 }
 
 success ( ) {
     echo
-    echo "${bold}${green} $* ${reset}"
+    echo "${bold}${green}$*${reset}"
     echo
 }
 
@@ -47,32 +59,52 @@ jsonq() {
 }
 
 ensure python 'https://www.python.org'
-ensure ant 'http://ant.apache.org/'
 INSTALLED_WATCHMAN=`command -v watchman`
 
-DEFAULT_BUCK_REPO="https://github.com/facebook/buck.git"
-DEFAULT_BUCK_INSTALL_DIR="$HOME/.gradle/caches/okbuck/buck"
-CUSTOM_BUCK_REPO=""
-CUSTOM_REMOTE_NAME="custom"
-OKBUCK_SUCCESS="$WORKING_DIR/build/okbuck.success"
-OKBUCK_DIR="$WORKING_DIR/.okbuck"
+OKBUCK_SUCCESS="$SCRIPT_DIR/build/okbuck.success"
+OKBUCK_DIR="$SCRIPT_DIR/.okbuck"
 MAX_DISPLAY_CHANGES=10
+WATCHMAN_TIMEOUT=10
+WATCHMAN_FAILED="WATCHMAN FAILED"
+BUCK_BINARY_DIR="$OKBUCK_DIR/cache/buck_binary"
+
+# Timeout a call and exit early. This can be called via timeout <time> <command>.
+timeout( ) {
+    perl -e 'alarm shift; exec @ARGV' "$@";
+}
 
 ensureWatch ( ) {
-    watchman watch-project $WORKING_DIR >/dev/null 2>&1
+    timeout $WATCHMAN_TIMEOUT watchman watch-project "$SCRIPT_DIR" >/dev/null 2>&1
+}
+
+removeWatch ( ) {
+    timeout $WATCHMAN_TIMEOUT watchman watch-del "$SCRIPT_DIR" >/dev/null 2>&1
 }
 
 getChanges ( ) {
     ensureWatch
-
-    WATCHED_CHANGES=`watchman --output-encoding=json --no-pretty -j 2>&1 <<-EOT
-["query", "$WORKING_DIR", {
+    WATCHMAN_ERROR_CODE=$?
+    if [[ $WATCHMAN_ERROR_CODE -ne 0 ]]; then
+        WATCHED_CHANGES=$WATCHMAN_FAILED
+        echo "watch-project failed after $WATCHMAN_TIMEOUT seconds, error code: $WATCHMAN_ERROR_CODE"
+        removeWatch
+        WATCHDEL_ERROR_CODE=$?
+        if [[ $WATCHDEL_ERROR_CODE -ne 0 ]]; then
+            echo "watch-del failed after $WATCHMAN_TIMEOUT seconds, error code: $?"
+            echo "Killing all watchman processes"
+            killall watchman || true
+        fi
+    else
+        WATCHED_CHANGES=`watchman --output-encoding=json --no-pretty -j 2>&1 <<-EOT
+["query", "$SCRIPT_DIR", {
     "since": "n:okbuck_trig",
     "expression": ["allof",
         ["type", "f"],
         ["anyof",
             ["suffix", "gradle"],
-            ["name", ["gradle-wrapper.properties", "lint.xml"]],
+            ["suffix", "map"],
+            ["suffix", "pro"],
+            ["name", ["lint.xml", "gradle-wrapper.properties"]],
             ["match", "**/src/**/AndroidManifest.xml", "wholename"]
         ],
         ["not",
@@ -83,7 +115,7 @@ getChanges ( ) {
 }]
 EOT`
     SOURCE_ROOTS=`watchman --output-encoding=json --no-pretty -j 2>&1 <<-EOT
-["query", "$WORKING_DIR", {
+["query", "$SCRIPT_DIR", {
     "since": "n:okbuck_source_roots",
     "expression": ["allof",
         ["type", "d"],
@@ -99,6 +131,7 @@ EOT`
     "fields": ["new", "exists", "name"]
 }]
 EOT`
+    fi
 }
 
 updateOkBuckSuccess ( ) {
@@ -112,56 +145,65 @@ runOkBuck ( ) {
     echo
 
     rm -f $OKBUCK_SUCCESS
-    ( $WORKING_DIR/gradlew -p $WORKING_DIR okbuck -Dokbuck.wrapper=true $EXTRA_OKBUCK_ARGS &&
+    ( "$SCRIPT_DIR/gradlew" -p "$SCRIPT_DIR" okbuck -Dokbuck.wrapper=true $EXTRA_OKBUCK_ARGS &&
     updateOkBuckSuccess && success "PROCEEDING WITH BUCK" ) || die "OKBUCK FAILED"
 }
 
 watchmanWorkflow ( ) {
     # Get list of changed files since last time by querying watchman
     getChanges
-
-    # Format list for simpler output
-    CHANGES=$(echo $WATCHED_CHANGES | jsonq '" ".join(obj["files"])')
-    NEW_OR_DELETED_SOURCE_ROOTS=$(echo $SOURCE_ROOTS | jsonq '" ".join([f["name"] for f in obj["files"] if (not f["exists"] or f["new"])])')
-    NUM_CHANGES=$(echo $CHANGES $NEW_OR_DELETED_SOURCE_ROOTS | wc -w)
-
-    if [[ $NUM_CHANGES -gt 0 ]]; then
-        info "CHANGES DETECTED IN:"
-        echo $CHANGES $NEW_OR_DELETED_SOURCE_ROOTS | tr ' ' '\n' | head -n $MAX_DISPLAY_CHANGES
-        if [[ $NUM_CHANGES -gt $MAX_DISPLAY_CHANGES ]]; then
-            DIFF=`expr $NUM_CHANGES - $MAX_DISPLAY_CHANGES`
-            echo "...and $DIFF more"
-        fi
-        echo
+    if [[ "$WATCHED_CHANGES" = "$WATCHMAN_FAILED" ]]; then
         runOkBuck
+    else
+        # Format list for simpler output
+        CHANGES=$(echo $WATCHED_CHANGES | jsonq '" ".join(obj["files"])')
+        NEW_OR_DELETED_SOURCE_ROOTS=$(echo $SOURCE_ROOTS | jsonq '" ".join([f["name"] for f in obj["files"] if (not f["exists"] or f["new"])])')
+        NUM_CHANGES=$(echo $CHANGES $NEW_OR_DELETED_SOURCE_ROOTS | wc -w)
+
+        if [[ $NUM_CHANGES -gt 0 ]]; then
+            info "CHANGES DETECTED IN:"
+            echo $CHANGES $NEW_OR_DELETED_SOURCE_ROOTS | tr ' ' '\n' | head -n $MAX_DISPLAY_CHANGES
+            if [[ $NUM_CHANGES -gt $MAX_DISPLAY_CHANGES ]]; then
+                DIFF=`expr $NUM_CHANGES - $MAX_DISPLAY_CHANGES`
+                echo "...and $DIFF more"
+            fi
+            echo
+            runOkBuck
+        fi
+    fi
+}
+
+killBuckDaemons ( ) {
+    DAEMONS=$(ps -ef | grep "[c]om.facebook.buck.cli.Main\$DaemonBootstrap" | awk '{print $2}')
+    if [ ! -z "$DAEMONS" ]; then
+        echo "$DAEMONS" | xargs kill -9
     fi
 }
 
 setupBuckBinary ( ) {
-    # If no explicit buck binary is set
-    if [[ -z "$BUCK_BINARY" ]] ; then
-        # If no buck installation directory is set
-        if [[ -z "$BUCK_HOME" ]]; then
-            BUCK_HOME=$DEFAULT_BUCK_INSTALL_DIR
-        fi
+    BUCK_BINARY=$(find "$BUCK_BINARY_DIR" -name buck-*.pex)
 
-        # Install buck from source if not already available
-        if [[ ! -d "$BUCK_HOME" ]]; then
-            warn "BUCK NOT FOUND IN '$BUCK_HOME'. INSTALLING BUCK..."
-            git clone $DEFAULT_BUCK_REPO $BUCK_HOME
-        fi
+    if [[ ! -x "$BUCK_BINARY" ]]; then
+        chmod +x "$BUCK_BINARY"
+    fi
 
-        # Add custom buck remote
-        if [[ ! -z $CUSTOM_BUCK_REPO ]]; then
-            cd $BUCK_HOME
-            REMOTE_EXISTS=$(git remote -v | grep "$CUSTOM_REMOTE_NAME")
-            if [[ -z "$REMOTE_EXISTS" ]]; then
-                git remote add $CUSTOM_REMOTE_NAME $CUSTOM_BUCK_REPO
-            fi
-            cd -
-        fi
+    # No existing daemon or clean project root
+    BUCKD_VERSION_FILE="$PROJECT_ROOT/.buckd/buckd.version"
+    if [[ ! -f "$BUCKD_VERSION_FILE" ]]; then
+        killBuckDaemons
+    else
+        BUCKD_VERSION=$(cat "$BUCKD_VERSION_FILE")
+    fi
 
-        BUCK_BINARY="$BUCK_HOME/bin/buck"
+    # Unknown daemon state
+    if [[ -z "$BUCKD_VERSION" ]]; then
+        killBuckDaemons
+    fi
+
+    # Daemon version does not match
+    BUCK_BINARY_VERSION=$(basename "$BUCK_BINARY" | cut -f 1 -d "." | cut -f 2 -d "-")
+    if [[ "$BUCK_BINARY_VERSION" != "$BUCKD_VERSION" ]]; then
+        killBuckDaemons
     fi
 }
 
@@ -192,10 +234,10 @@ setupBuckRun ( ) {
 
 # Handle parameters and flags
 handleParams ( ) {
-    # Go directly to kill. Do not run okbuck.
-    if [[ "kill" == $1 ]]; then
-        SKIP_OKBUCK=true
-    fi
+   # Go directly to the kill command, help command, or --help option. Do not run okbuck.
+   if [[ "kill" == $1 || "help" == $1 || $@ == *"--help"* || $@ == *"-h"* ]]; then
+      SKIP_OKBUCK=true
+   fi
 }
 
 handleParams "$@"
