Fix buck build on travis

diff --git a/buckw b/buckw
--- a/buckw
+++ b/buckw
@@ -4,7 +4,7 @@
 ##
 ##  Buck wrapper script to invoke okbuck when needed, before running buck
 ##
-##  Created by OkBuck Gradle Plugin on : Thu Dec 15 23:45:23 PST 2016
+##  Created by OkBuck Gradle Plugin on : Sun Dec 18 12:19:24 PST 2016
 ##
 #########################################################################
 
@@ -60,6 +60,10 @@ MAX_DISPLAY_CHANGES=10
 
 ensureWatch ( ) {
     watchman watch-project $WORKING_DIR >/dev/null 2>&1
+}
+
+removeWatch ( ) {
+    watchman watch-del $WORKING_DIR >/dev/null 2>&1
 }
 
 getToClean ( ) {
@@ -127,9 +131,15 @@ runOkBuck ( ) {
     echo
 
     if [[ ! -z "$INSTALLED_WATCHMAN" ]]; then
-        getToClean | jsonq '"\n".join(obj["files"])' | xargs rm
-        info "DELETED OLD BUCK FILES"
-        EXTRA_OKBUCK_ARGS="-xokbuckClean $EXTRA_OKBUCK_ARGS"
+        TO_CLEAN=$(getToClean | jsonq '"\n".join(obj["files"])')
+        if [[ $? -eq 0 ]]; then
+            echo $TO_CLEAN | xargs rm
+            info "DELETED OLD BUCK FILES"
+            EXTRA_OKBUCK_ARGS="-xokbuckClean $EXTRA_OKBUCK_ARGS"
+        else
+            warn "WATCHMAN FAILED. USING OKBUCKCLEAN."
+            removeWatch
+        fi
     fi
 
     rm -f $OKBUCK_SUCCESS
